name: Code Addition Request 📜
description: Requesting for the new project/algorithm addition to contribute to this repository.
title: "[Code Addition Request]: "
body:
  - type: checkboxes
    id: existing-issue
    attributes:
      label: Have you completed your first issue?
      description: Please confirm that all other PRs related to issues have been approved and merged.
      options:
        - label: I have completed my first issue
          required: true

  - type: checkboxes
    id: guidelines
    attributes:
      label: Guidelines
      options:
        - label: "I have read the guidelines"
          required: true
        - label: "I have the link to my latest merged PR"
          required: false

  - type: textarea
    id: latest-pr-link
    attributes:
      label: Latest Merged PR Link
      description: Please provide the link to the latest merged PR.
      placeholder: Enter the URL of the latest merged PR here.
    validations:
      required: true

  - type: textarea
    id: project-description
    attributes:
      label: Project Description
      description: Please provide a brief explanation of the new project or algorithm you want to add.
      placeholder: Describe the new project or algorithm you wish to contribute.
    validations:
      required: true

  - type: textarea
    id: full-name
    attributes:
      label: Full Name
      description: Please enter your full name.
      placeholder: Enter your full name here.
    validations:
      required: true

  - type: textarea
    id: participant-role
    attributes:
      label: Participant Role
      description: Please mention your role in the Open Source Program (e.g., GSOC, GSSOC, SSOC, JWOC).
      placeholder: Enter your participant role here.
    validations:
      required: true
